version: "3"

# based from https://gist.github.com/pkhabazi/51e9049b643d71c025c0d65df5792b3f
volumes:
  pihole:
services:
    # Pihole DNS server
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      hostname: pi-hole
      ports:
        - '53:53/tcp'
        - '53:53/udp'
        - '67:67/udp'
        - '80:80/tcp'
        - '443:443/tcp'
      environment:
        TZ: 'Asia/Manila'
        WEBPASSWORD: A6zyIcN_
        ServerIP: 10.36.38.100
        VIRTUAL_PORT: 80
      # Volumes store your data between container upgrades
      volumes:
        - ./etc-pihole/:/etc/pihole/
        - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
      dns:
        - 127.0.0.1
        - 1.1.1.1
      cap_add:
        - NET_ADMIN
      restart: unless-stopped
      network_mode: host